# Generated by Django 5.2.5 on 2025-12-03 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_management', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='contact',
        ),
        migrations.AddField(
            model_name='borrower',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='borrower',
            name='phone',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
