# Generated by Django 5.2.5 on 2025-12-03 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_management', '0002_remove_borrower_contact_borrower_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='email',
        ),
        migrations.RemoveField(
            model_name='borrower',
            name='phone',
        ),
        migrations.AddField(
            model_name='borrower',
            name='contact',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='book',
            name='isbn',
            field=models.CharField(max_length=13, unique=True),
        ),
        migrations.CreateModel(
            name='BookLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelf', models.IntegerField()),
                ('row', models.IntegerField()),
                ('column', models.IntegerField()),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location', to='lib_management.book')),
            ],
        ),
    ]
