# Generated by Django 5.2.5 on 2025-12-03 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_management', '0003_remove_borrower_email_remove_borrower_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('BORROW', 'Borrow'), ('RETURN', 'Return')], max_length=10),
        ),
    ]
