# Generated by Django 5.2.5 on 2025-12-03 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_management', '0004_borrower_email_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrower',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='borrower',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
