# Generated by Django 5.2.5 on 2025-12-03 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lib_management', '0006_remove_transaction_book_remove_transaction_borrower_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='borrower',
            name='contact',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
    ]
